### ISSUE TITLE
Combine with Architectury

### ISSUE THREAD

**Issue by RubixDev** [ReplayMod/preprocessor#15]
Is it possible to use this preprocesor in conjunction with an Architectury multiplatform project setup? I haven't been able to get it working yet, and would like to know if it's even possible. I love the benefits of a multi-version project using this preprocessor and don't really want to give them up just because I'm starting to go multi-platform.

**Comment by tr7zw** [comment]
I'm using my own cursed setup to spawn arch loom builds for 1.16.5-1.20.4 Fabric/Forge/NeoForge with preprocessor, so yes it is possible. https://github.com/tr7zw/ProcessedModTemplate Used for example by 3d skin layers.

**Comment by RubixDev** [comment]
thanks for the response. I actually already stumbled across your template by now and it helped me with my own setup, which is a bit different from yours. The preprocessor node graph looks like this in my case:
![Inventorio_Gradle_Modules](https://github.com/ReplayMod/preprocessor/assets/35602040/50613cc0-7adb-483c-8ada-d1625aba6480)

I just haven't made it public yet, but i'll post a link and close this issue once I have.

**Comment by RubixDev** [comment]
I'm using this setup for [Inventorio](https://github.com/RubixDev/Inventorio) now. Anyone else interested can have a look there, I also explained some extra bits [in the readme](https://github.com/RubixDev/Inventorio#contributing).
